name: Update Sitemap HTML

on:
  schedule:
    - cron: '0 0 * * *' # Ogni giorno a mezzanotte
  workflow_dispatch: # Permette l'avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Versione aggiornata

      - name: Set up Python
        uses: actions/setup-python@v5 # Versione aggiornata
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run converter
        run: python converter.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "Sitemap Bot"
          git config --global user.email "bot@github.com"
          git add sitemap-embed.html
          git commit -m "Update sitemap HTML" || exit 0
          git push
